### ISSUE TITLE
This repository is over its data quota. Can you offer google drive or dropbox link for basketballModel.pt

### ISSUE THREAD

**Issue by jjwwcc** [ayushpai/Basketball-Travel-Detector#3]
Downloading basketballModel.pt (90 MB)
Error downloading object: basketballModel.pt (3a0dacb): Smudge error: Error downloading basketballModel.pt (3a0dacb4f2fc70148134d0f638dfadc30d56f6c5e223286940c55c473205d727): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by EveCharbie** [comment]
I have the same issue :(
Is there a workaround?
