### ISSUE TITLE
Sequence issue

### ISSUE THREAD

**Issue by rikkardochaplin** [ayushpai/Basketball-Travel-Detector#4]
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 32.

**Comment by DanggoRyo** [comment]
If you change the line 57
rounded_results = np.round(pose_results[0].keypoints.numpy(), 1)
to
rounded_results = pose_results[0].keypoints.numpy()
it could be run, but I'm not sure if making this change will affect accuracy.

**Comment by rikkardochaplin** [comment]
okay bro I'll try thanks

**Comment by rikkardochaplin** [comment]
this not working

**Comment by jyt13** [comment]
> ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 32.

Hi, I try to use pose_results[0].keypoints.data.numpy(), and it works. You can print the keypoints to check the structure and also check the code in that script, it seems that keypoints.data is the data we need.

**Comment by ayushpai** [comment]
Yeah, pose_results[0].keypoints.data.numpy(), should work.
